import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'en' | 'pl' | 'de' | 'fr' | 'es' | 'it';

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.mepTracker': 'MEP Tracker',
    'nav.votingExplorer': 'Voting Explorer',
    'nav.countryMonitor': 'Country Monitor',
    'nav.committees': 'Committees',
    'nav.statistics': 'Statistics',
    // Dashboard
    'dashboard.title': 'European Parliament Explorer',
    'dashboard.subtitle': 'Explore data about Members of the European Parliament, voting patterns, committees, and political groups. Track how your representatives vote on key issues.',
    'dashboard.browseMeps': 'Browse MEPs',
    'dashboard.exploreVotes': 'Explore Votes',
    'dashboard.countryMonitor': 'Country Monitor',
    'dashboard.totalMeps': 'Total MEPs',
    'dashboard.politicalGroups': 'Political Groups',
    'dashboard.memberStates': 'Member States',
    'dashboard.trackedVotes': 'Tracked Votes',
    'dashboard.groups': 'Political Groups',
    'dashboard.seatsByCountry': 'Seats by Country (Top 10)',
    'dashboard.recentVotes': 'Recent Key Votes',
    'dashboard.viewAllVotes': 'View all votes',
    'dashboard.passed': 'Passed',
    'dashboard.rejected': 'Rejected',
    'dashboard.hemicycle': 'Parliament Hemicycle',
    'dashboard.hemicycleDesc': '720 seats arranged by political group',
    'dashboard.mepTracker': 'MEP Tracker',
    'dashboard.mepTrackerDesc': 'Search and filter all {count} Members of the European Parliament',
    'dashboard.committeesDesc': 'Explore 20 parliamentary committees and their members',
    'dashboard.countryMonitorDesc': 'Deep dive into any EU member state\'s representation',
    // MEP Tracker
    'meps.title': 'MEP Tracker',
    'meps.subtitle': 'Search and explore Members of the European Parliament',
    'meps.searchPlaceholder': 'Search MEPs by name or party...',
    'meps.allCountries': 'All Countries',
    'meps.allGroups': 'All Political Groups',
    'meps.allCommittees': 'All Committees',
    'meps.results': '{count} result(s)',
    'meps.clearFilters': 'Clear all filters',
    'meps.noResults': 'No MEPs found',
    'meps.noResultsHint': 'Try adjusting your search or filters',
    'meps.previous': 'Previous',
    'meps.next': 'Next',
    'meps.page': 'Page {current} of {total}',
    'meps.filters': 'Filters',
    // Voting Explorer
    'votes.title': 'Voting Explorer',
    'votes.subtitle': 'Explore how political groups voted on key European Parliament issues',
    'votes.byTopic': 'Votes by Topic',
    'votes.searchPlaceholder': 'Search votes by title...',
    'votes.found': '{count} votes found',
    'votes.for': 'For',
    'votes.against': 'Against',
    'votes.abstention': 'Abstention',
    'votes.passed': 'Passed',
    'votes.rejected': 'Rejected',
    'votes.breakdown': 'Vote breakdown by Political Group',
    'votes.group': 'Group',
    // Country Monitor
    'country.title': 'Country Monitor',
    'country.subtitle': 'Deep dive into any EU member state\'s parliamentary representation',
    'country.selectPrompt': 'Select a country to explore',
    'country.selectDesc': 'Choose an EU member state to see detailed analysis of its MEPs',
    'country.meps': '{country} MEPs',
    'country.nationalParties': 'National Parties',
    'country.epGroups': 'EP Groups',
    'country.genderBalance': 'Gender Balance',
    'country.byParty': 'By National Party',
    'country.byGroup': 'By EP Political Group',
    'country.partyToGroup': '{country} Parties in EP Groups',
    'country.allMeps': 'All {country} MEPs',
    'country.searchPlaceholder': 'Search {country} MEPs...',
    'country.noResults': 'No MEPs match your search criteria',
    'country.outOf': 'out of 720 total',
    // Committee Explorer
    'committees.title': 'Committee Explorer',
    'committees.subtitle': 'Explore parliamentary committees and their members',
    'committees.searchPlaceholder': 'Search committees...',
    'committees.selectPrompt': 'Select a committee',
    'committees.selectDesc': 'Choose a committee from the list to see its members and composition',
    'committees.members': '{count} members',
    'committees.groupComposition': 'Political Group Composition',
    'committees.topCountries': 'Top Countries',
    'committees.membersList': 'Members',
    // Statistics
    'stats.title': 'Parliament Statistics',
    'stats.subtitle': 'Comprehensive statistics about the European Parliament composition',
    'stats.seatsByCountry': 'Seat Distribution by Country',
    'stats.genderBalance': 'Gender Balance',
    'stats.groupSizes': 'Political Group Sizes',
    'stats.countryGroups': 'Political Groups by Country (Top 15)',
    'stats.allCountries': 'All Countries',
    'stats.country': 'Country',
    'stats.totalSeats': 'Total Seats',
    'stats.mepsListed': 'MEPs Listed',
    'stats.female': 'Female',
    'stats.male': 'Male',
    // Footer
    'footer.title': 'OpenParliment - European Parliament Data Explorer',
    'footer.dataFrom': 'Data from',
    'footer.portal': 'EU Parliament Open Data Portal',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.allTopics': 'All Topics',
    'common.back': 'Back',
  },
  pl: {
    'nav.dashboard': 'Pulpit',
    'nav.mepTracker': 'Wyszukiwarka MEP',
    'nav.votingExplorer': 'Explorer Glosowań',
    'nav.countryMonitor': 'Monitor Kraju',
    'nav.committees': 'Komisje',
    'nav.statistics': 'Statystyki',
    'dashboard.title': 'Explorer Parlamentu Europejskiego',
    'dashboard.subtitle': 'Przeglądaj dane o posłach do Parlamentu Europejskiego, wzorcach głosowań, komisjach i grupach politycznych. Śledź jak Twoi przedstawiciele głosują.',
    'dashboard.browseMeps': 'Przeglądaj posłów',
    'dashboard.exploreVotes': 'Przeglądaj głosowania',
    'dashboard.countryMonitor': 'Monitor Kraju',
    'dashboard.totalMeps': 'Łącznie posłów',
    'dashboard.politicalGroups': 'Grupy polityczne',
    'dashboard.memberStates': 'Państwa członkowskie',
    'dashboard.trackedVotes': 'Śledzonych głosowań',
    'dashboard.groups': 'Grupy polityczne',
    'dashboard.seatsByCountry': 'Miejsca wg kraju (Top 10)',
    'dashboard.recentVotes': 'Ostatnie kluczowe głosowania',
    'dashboard.viewAllVotes': 'Wszystkie głosowania',
    'dashboard.passed': 'Przyjęte',
    'dashboard.rejected': 'Odrzucone',
    'dashboard.hemicycle': 'Hemicykl Parlamentu',
    'dashboard.hemicycleDesc': '720 miejsc ułożonych wg grupy politycznej',
    'dashboard.mepTracker': 'Wyszukiwarka posłów',
    'dashboard.mepTrackerDesc': 'Szukaj i filtruj wszystkich {count} posłów do PE',
    'dashboard.committeesDesc': 'Przeglądaj 20 komisji parlamentarnych i ich członków',
    'dashboard.countryMonitorDesc': 'Szczegółowa analiza reprezentacji dowolnego państwa członkowskiego',
    'meps.title': 'Wyszukiwarka MEP',
    'meps.subtitle': 'Szukaj i przeglądaj posłów do Parlamentu Europejskiego',
    'meps.searchPlaceholder': 'Szukaj posłów po nazwisku lub partii...',
    'meps.allCountries': 'Wszystkie kraje',
    'meps.allGroups': 'Wszystkie grupy polityczne',
    'meps.allCommittees': 'Wszystkie komisje',
    'meps.results': '{count} wyników',
    'meps.clearFilters': 'Wyczyść filtry',
    'meps.noResults': 'Nie znaleziono posłów',
    'meps.noResultsHint': 'Spróbuj zmienić kryteria wyszukiwania',
    'meps.previous': 'Poprzednia',
    'meps.next': 'Następna',
    'meps.page': 'Strona {current} z {total}',
    'meps.filters': 'Filtry',
    'votes.title': 'Explorer Głosowań',
    'votes.subtitle': 'Sprawdź jak grupy polityczne głosowały w Parlamencie Europejskim',
    'votes.byTopic': 'Głosowania wg tematu',
    'votes.searchPlaceholder': 'Szukaj głosowań...',
    'votes.found': '{count} głosowań',
    'votes.for': 'Za',
    'votes.against': 'Przeciw',
    'votes.abstention': 'Wstrzymanie',
    'votes.passed': 'Przyjęte',
    'votes.rejected': 'Odrzucone',
    'votes.breakdown': 'Rozkład głosów wg grupy politycznej',
    'votes.group': 'Grupa',
    'country.title': 'Monitor Kraju',
    'country.subtitle': 'Szczegółowa analiza reprezentacji parlamentarnej dowolnego państwa członkowskiego UE',
    'country.selectPrompt': 'Wybierz kraj do analizy',
    'country.selectDesc': 'Wybierz państwo członkowskie UE, aby zobaczyć szczegółową analizę posłów',
    'country.meps': 'Posłowie z {country}',
    'country.nationalParties': 'Partie krajowe',
    'country.epGroups': 'Grupy PE',
    'country.genderBalance': 'Balans płci',
    'country.byParty': 'Wg partii krajowej',
    'country.byGroup': 'Wg grupy PE',
    'country.partyToGroup': 'Partie {country} w grupach PE',
    'country.allMeps': 'Wszyscy posłowie z {country}',
    'country.searchPlaceholder': 'Szukaj posłów z {country}...',
    'country.noResults': 'Brak wyników',
    'country.outOf': 'z 720 łącznie',
    'committees.title': 'Explorer Komisji',
    'committees.subtitle': 'Przeglądaj komisje parlamentarne i ich członków',
    'committees.searchPlaceholder': 'Szukaj komisji...',
    'committees.selectPrompt': 'Wybierz komisję',
    'committees.selectDesc': 'Wybierz komisję z listy, aby zobaczyć skład i członków',
    'committees.members': '{count} członków',
    'committees.groupComposition': 'Skład wg grupy politycznej',
    'committees.topCountries': 'Najliczniej reprezentowane kraje',
    'committees.membersList': 'Członkowie',
    'stats.title': 'Statystyki Parlamentu',
    'stats.subtitle': 'Kompleksowe statystyki Parlamentu Europejskiego',
    'stats.seatsByCountry': 'Rozkład miejsc wg kraju',
    'stats.genderBalance': 'Balans płci',
    'stats.groupSizes': 'Wielkość grup politycznych',
    'stats.countryGroups': 'Grupy polityczne wg kraju (Top 15)',
    'stats.allCountries': 'Wszystkie kraje',
    'stats.country': 'Kraj',
    'stats.totalSeats': 'Miejsca',
    'stats.mepsListed': 'Posłów',
    'stats.female': 'Kobiety',
    'stats.male': 'Mężczyźni',
    'footer.title': 'OpenParliment - Explorer danych Parlamentu Europejskiego',
    'footer.dataFrom': 'Dane z',
    'footer.portal': 'Portal Otwartych Danych PE',
    'common.loading': 'Ładowanie...',
    'common.error': 'Coś poszło nie tak',
    'common.retry': 'Spróbuj ponownie',
    'common.allTopics': 'Wszystkie tematy',
    'common.back': 'Wstecz',
  },
  de: {
    'nav.dashboard': 'Übersicht',
    'nav.mepTracker': 'MdEP Suche',
    'nav.votingExplorer': 'Abstimmungs-Explorer',
    'nav.countryMonitor': 'Länder-Monitor',
    'nav.committees': 'Ausschüsse',
    'nav.statistics': 'Statistiken',
    'dashboard.title': 'Europäisches Parlament Explorer',
    'dashboard.subtitle': 'Erkunden Sie Daten über die Mitglieder des Europäischen Parlaments, Abstimmungsmuster, Ausschüsse und Fraktionen.',
    'dashboard.browseMeps': 'MdEP durchsuchen',
    'dashboard.exploreVotes': 'Abstimmungen',
    'dashboard.countryMonitor': 'Länder-Monitor',
    'dashboard.totalMeps': 'MdEP gesamt',
    'dashboard.politicalGroups': 'Fraktionen',
    'dashboard.memberStates': 'Mitgliedstaaten',
    'dashboard.trackedVotes': 'Abstimmungen',
    'dashboard.groups': 'Fraktionen',
    'dashboard.seatsByCountry': 'Sitze nach Land (Top 10)',
    'dashboard.recentVotes': 'Letzte Abstimmungen',
    'dashboard.viewAllVotes': 'Alle Abstimmungen',
    'dashboard.passed': 'Angenommen',
    'dashboard.rejected': 'Abgelehnt',
    'dashboard.hemicycle': 'Plenarsaal',
    'dashboard.hemicycleDesc': '720 Sitze nach Fraktion angeordnet',
    'dashboard.mepTracker': 'MdEP Suche',
    'dashboard.mepTrackerDesc': 'Suchen und filtern Sie alle {count} MdEP',
    'dashboard.committeesDesc': 'Erkunden Sie 20 parlamentarische Ausschüsse',
    'dashboard.countryMonitorDesc': 'Detailanalyse der Vertretung eines Mitgliedstaats',
    'meps.title': 'MdEP Suche',
    'meps.subtitle': 'Suchen Sie Mitglieder des Europäischen Parlaments',
    'meps.searchPlaceholder': 'MdEP nach Name oder Partei suchen...',
    'meps.allCountries': 'Alle Länder',
    'meps.allGroups': 'Alle Fraktionen',
    'meps.allCommittees': 'Alle Ausschüsse',
    'meps.results': '{count} Ergebnis(se)',
    'meps.clearFilters': 'Filter zurücksetzen',
    'meps.noResults': 'Keine MdEP gefunden',
    'meps.noResultsHint': 'Passen Sie Ihre Suche an',
    'meps.previous': 'Zurück',
    'meps.next': 'Weiter',
    'meps.page': 'Seite {current} von {total}',
    'meps.filters': 'Filter',
    'votes.title': 'Abstimmungs-Explorer',
    'votes.subtitle': 'Erkunden Sie das Abstimmungsverhalten der Fraktionen',
    'votes.byTopic': 'Abstimmungen nach Thema',
    'votes.searchPlaceholder': 'Abstimmungen suchen...',
    'votes.found': '{count} Abstimmungen',
    'votes.for': 'Dafür',
    'votes.against': 'Dagegen',
    'votes.abstention': 'Enthaltung',
    'votes.passed': 'Angenommen',
    'votes.rejected': 'Abgelehnt',
    'votes.breakdown': 'Abstimmungsergebnis nach Fraktion',
    'votes.group': 'Fraktion',
    'country.title': 'Länder-Monitor',
    'country.subtitle': 'Detailanalyse der parlamentarischen Vertretung eines EU-Mitgliedstaats',
    'country.selectPrompt': 'Land auswählen',
    'country.selectDesc': 'Wählen Sie einen EU-Mitgliedstaat',
    'country.meps': 'MdEP aus {country}',
    'country.nationalParties': 'Nationale Parteien',
    'country.epGroups': 'EP Fraktionen',
    'country.genderBalance': 'Geschlechterbalance',
    'country.byParty': 'Nach nationaler Partei',
    'country.byGroup': 'Nach EP Fraktion',
    'country.partyToGroup': '{country} Parteien in EP Fraktionen',
    'country.allMeps': 'Alle MdEP aus {country}',
    'country.searchPlaceholder': '{country} MdEP suchen...',
    'country.noResults': 'Keine Ergebnisse',
    'country.outOf': 'von 720 gesamt',
    'committees.title': 'Ausschuss-Explorer',
    'committees.subtitle': 'Erkunden Sie parlamentarische Ausschüsse und ihre Mitglieder',
    'committees.searchPlaceholder': 'Ausschüsse suchen...',
    'committees.selectPrompt': 'Ausschuss auswählen',
    'committees.selectDesc': 'Wählen Sie einen Ausschuss aus der Liste',
    'committees.members': '{count} Mitglieder',
    'committees.groupComposition': 'Zusammensetzung nach Fraktion',
    'committees.topCountries': 'Top Länder',
    'committees.membersList': 'Mitglieder',
    'stats.title': 'Parlamentsstatistiken',
    'stats.subtitle': 'Umfassende Statistiken zum Europäischen Parlament',
    'stats.seatsByCountry': 'Sitzverteilung nach Land',
    'stats.genderBalance': 'Geschlechterbalance',
    'stats.groupSizes': 'Fraktionsgrößen',
    'stats.countryGroups': 'Fraktionen nach Land (Top 15)',
    'stats.allCountries': 'Alle Länder',
    'stats.country': 'Land',
    'stats.totalSeats': 'Sitze',
    'stats.mepsListed': 'MdEP',
    'stats.female': 'Weiblich',
    'stats.male': 'Männlich',
    'footer.title': 'OpenParliment - Europäisches Parlament Daten-Explorer',
    'footer.dataFrom': 'Daten von',
    'footer.portal': 'EU Parlament Open Data Portal',
    'common.loading': 'Laden...',
    'common.error': 'Etwas ist schiefgelaufen',
    'common.retry': 'Erneut versuchen',
    'common.allTopics': 'Alle Themen',
    'common.back': 'Zurück',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.mepTracker': 'Recherche MPE',
    'nav.votingExplorer': 'Explorateur de votes',
    'nav.countryMonitor': 'Moniteur par pays',
    'nav.committees': 'Commissions',
    'nav.statistics': 'Statistiques',
    'dashboard.title': 'Explorateur du Parlement Européen',
    'dashboard.subtitle': 'Explorez les données sur les députés européens, les votes, les commissions et les groupes politiques.',
    'dashboard.browseMeps': 'Parcourir les MPE',
    'dashboard.exploreVotes': 'Explorer les votes',
    'dashboard.countryMonitor': 'Moniteur par pays',
    'dashboard.totalMeps': 'Total MPE',
    'dashboard.politicalGroups': 'Groupes politiques',
    'dashboard.memberStates': 'États membres',
    'dashboard.trackedVotes': 'Votes suivis',
    'dashboard.groups': 'Groupes politiques',
    'dashboard.seatsByCountry': 'Sièges par pays (Top 10)',
    'dashboard.recentVotes': 'Derniers votes clés',
    'dashboard.viewAllVotes': 'Voir tous les votes',
    'dashboard.passed': 'Adopté',
    'dashboard.rejected': 'Rejeté',
    'dashboard.hemicycle': 'Hémicycle parlementaire',
    'dashboard.hemicycleDesc': '720 sièges par groupe politique',
    'dashboard.mepTracker': 'Recherche MPE',
    'dashboard.mepTrackerDesc': 'Recherchez et filtrez les {count} députés européens',
    'dashboard.committeesDesc': 'Explorez 20 commissions parlementaires et leurs membres',
    'dashboard.countryMonitorDesc': 'Analyse approfondie de la représentation d\'un État membre',
    'meps.title': 'Recherche MPE',
    'meps.subtitle': 'Recherchez les membres du Parlement européen',
    'meps.searchPlaceholder': 'Rechercher par nom ou parti...',
    'meps.allCountries': 'Tous les pays',
    'meps.allGroups': 'Tous les groupes',
    'meps.allCommittees': 'Toutes les commissions',
    'meps.results': '{count} résultat(s)',
    'meps.clearFilters': 'Réinitialiser les filtres',
    'meps.noResults': 'Aucun MPE trouvé',
    'meps.noResultsHint': 'Modifiez vos critères de recherche',
    'meps.previous': 'Précédent',
    'meps.next': 'Suivant',
    'meps.page': 'Page {current} sur {total}',
    'meps.filters': 'Filtres',
    'votes.title': 'Explorateur de votes',
    'votes.subtitle': 'Découvrez comment les groupes politiques ont voté',
    'votes.byTopic': 'Votes par sujet',
    'votes.searchPlaceholder': 'Rechercher des votes...',
    'votes.found': '{count} votes',
    'votes.for': 'Pour',
    'votes.against': 'Contre',
    'votes.abstention': 'Abstention',
    'votes.passed': 'Adopté',
    'votes.rejected': 'Rejeté',
    'votes.breakdown': 'Répartition des votes par groupe politique',
    'votes.group': 'Groupe',
    'country.title': 'Moniteur par pays',
    'country.subtitle': 'Analyse approfondie de la représentation parlementaire d\'un État membre',
    'country.selectPrompt': 'Sélectionnez un pays',
    'country.selectDesc': 'Choisissez un État membre de l\'UE',
    'country.meps': 'MPE de {country}',
    'country.nationalParties': 'Partis nationaux',
    'country.epGroups': 'Groupes PE',
    'country.genderBalance': 'Équilibre des genres',
    'country.byParty': 'Par parti national',
    'country.byGroup': 'Par groupe PE',
    'country.partyToGroup': 'Partis {country} dans les groupes PE',
    'country.allMeps': 'Tous les MPE de {country}',
    'country.searchPlaceholder': 'Rechercher MPE de {country}...',
    'country.noResults': 'Aucun résultat',
    'country.outOf': 'sur 720 au total',
    'committees.title': 'Explorateur de commissions',
    'committees.subtitle': 'Explorez les commissions parlementaires et leurs membres',
    'committees.searchPlaceholder': 'Rechercher des commissions...',
    'committees.selectPrompt': 'Sélectionnez une commission',
    'committees.selectDesc': 'Choisissez une commission dans la liste',
    'committees.members': '{count} membres',
    'committees.groupComposition': 'Composition par groupe politique',
    'committees.topCountries': 'Principaux pays',
    'committees.membersList': 'Membres',
    'stats.title': 'Statistiques du Parlement',
    'stats.subtitle': 'Statistiques complètes sur la composition du Parlement européen',
    'stats.seatsByCountry': 'Répartition des sièges par pays',
    'stats.genderBalance': 'Équilibre des genres',
    'stats.groupSizes': 'Taille des groupes politiques',
    'stats.countryGroups': 'Groupes politiques par pays (Top 15)',
    'stats.allCountries': 'Tous les pays',
    'stats.country': 'Pays',
    'stats.totalSeats': 'Total sièges',
    'stats.mepsListed': 'MPE listés',
    'stats.female': 'Femmes',
    'stats.male': 'Hommes',
    'footer.title': 'OpenParliment - Explorateur de données du Parlement européen',
    'footer.dataFrom': 'Données de',
    'footer.portal': 'Portail Open Data du PE',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.retry': 'Réessayer',
    'common.allTopics': 'Tous les sujets',
    'common.back': 'Retour',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.mepTracker': 'Buscador MEP',
    'nav.votingExplorer': 'Explorador de votos',
    'nav.countryMonitor': 'Monitor de país',
    'nav.committees': 'Comisiones',
    'nav.statistics': 'Estadísticas',
    'dashboard.title': 'Explorador del Parlamento Europeo',
    'dashboard.subtitle': 'Explore datos sobre los eurodiputados, patrones de votación, comisiones y grupos políticos.',
    'dashboard.browseMeps': 'Buscar MEP',
    'dashboard.exploreVotes': 'Explorar votos',
    'dashboard.countryMonitor': 'Monitor de país',
    'dashboard.totalMeps': 'Total MEP',
    'dashboard.politicalGroups': 'Grupos políticos',
    'dashboard.memberStates': 'Estados miembros',
    'dashboard.trackedVotes': 'Votos registrados',
    'dashboard.groups': 'Grupos políticos',
    'dashboard.seatsByCountry': 'Escaños por país (Top 10)',
    'dashboard.recentVotes': 'Últimas votaciones clave',
    'dashboard.viewAllVotes': 'Ver todos los votos',
    'dashboard.passed': 'Aprobado',
    'dashboard.rejected': 'Rechazado',
    'dashboard.hemicycle': 'Hemiciclo parlamentario',
    'dashboard.hemicycleDesc': '720 escaños por grupo político',
    'dashboard.mepTracker': 'Buscador MEP',
    'dashboard.mepTrackerDesc': 'Busque y filtre los {count} eurodiputados',
    'dashboard.committeesDesc': 'Explore 20 comisiones parlamentarias y sus miembros',
    'dashboard.countryMonitorDesc': 'Análisis detallado de la representación de cualquier estado miembro',
    'meps.title': 'Buscador MEP',
    'meps.subtitle': 'Busque eurodiputados del Parlamento Europeo',
    'meps.searchPlaceholder': 'Buscar por nombre o partido...',
    'meps.allCountries': 'Todos los países',
    'meps.allGroups': 'Todos los grupos',
    'meps.allCommittees': 'Todas las comisiones',
    'meps.results': '{count} resultado(s)',
    'meps.clearFilters': 'Limpiar filtros',
    'meps.noResults': 'No se encontraron MEP',
    'meps.noResultsHint': 'Ajuste sus criterios de búsqueda',
    'meps.previous': 'Anterior',
    'meps.next': 'Siguiente',
    'meps.page': 'Página {current} de {total}',
    'meps.filters': 'Filtros',
    'votes.title': 'Explorador de votos',
    'votes.subtitle': 'Descubra cómo votaron los grupos políticos',
    'votes.byTopic': 'Votos por tema',
    'votes.searchPlaceholder': 'Buscar votos...',
    'votes.found': '{count} votos',
    'votes.for': 'A favor',
    'votes.against': 'En contra',
    'votes.abstention': 'Abstención',
    'votes.passed': 'Aprobado',
    'votes.rejected': 'Rechazado',
    'votes.breakdown': 'Desglose de votos por grupo político',
    'votes.group': 'Grupo',
    'country.title': 'Monitor de país',
    'country.subtitle': 'Análisis detallado de la representación parlamentaria de un estado miembro',
    'country.selectPrompt': 'Seleccione un país',
    'country.selectDesc': 'Elija un estado miembro de la UE',
    'country.meps': 'MEP de {country}',
    'country.nationalParties': 'Partidos nacionales',
    'country.epGroups': 'Grupos PE',
    'country.genderBalance': 'Balance de género',
    'country.byParty': 'Por partido nacional',
    'country.byGroup': 'Por grupo PE',
    'country.partyToGroup': 'Partidos de {country} en grupos PE',
    'country.allMeps': 'Todos los MEP de {country}',
    'country.searchPlaceholder': 'Buscar MEP de {country}...',
    'country.noResults': 'Sin resultados',
    'country.outOf': 'de 720 en total',
    'committees.title': 'Explorador de comisiones',
    'committees.subtitle': 'Explore comisiones parlamentarias y sus miembros',
    'committees.searchPlaceholder': 'Buscar comisiones...',
    'committees.selectPrompt': 'Seleccione una comisión',
    'committees.selectDesc': 'Elija una comisión de la lista',
    'committees.members': '{count} miembros',
    'committees.groupComposition': 'Composición por grupo político',
    'committees.topCountries': 'Principales países',
    'committees.membersList': 'Miembros',
    'stats.title': 'Estadísticas del Parlamento',
    'stats.subtitle': 'Estadísticas completas de la composición del Parlamento Europeo',
    'stats.seatsByCountry': 'Distribución de escaños por país',
    'stats.genderBalance': 'Balance de género',
    'stats.groupSizes': 'Tamaño de grupos políticos',
    'stats.countryGroups': 'Grupos políticos por país (Top 15)',
    'stats.allCountries': 'Todos los países',
    'stats.country': 'País',
    'stats.totalSeats': 'Total escaños',
    'stats.mepsListed': 'MEP listados',
    'stats.female': 'Mujeres',
    'stats.male': 'Hombres',
    'footer.title': 'OpenParliment - Explorador de datos del Parlamento Europeo',
    'footer.dataFrom': 'Datos de',
    'footer.portal': 'Portal Open Data del PE',
    'common.loading': 'Cargando...',
    'common.error': 'Algo salió mal',
    'common.retry': 'Reintentar',
    'common.allTopics': 'Todos los temas',
    'common.back': 'Volver',
  },
  it: {
    'nav.dashboard': 'Pannello',
    'nav.mepTracker': 'Ricerca MEP',
    'nav.votingExplorer': 'Esploratore voti',
    'nav.countryMonitor': 'Monitor paese',
    'nav.committees': 'Commissioni',
    'nav.statistics': 'Statistiche',
    'dashboard.title': 'Esploratore del Parlamento Europeo',
    'dashboard.subtitle': 'Esplora i dati sui membri del Parlamento Europeo, i modelli di voto, le commissioni e i gruppi politici.',
    'dashboard.browseMeps': 'Cerca MEP',
    'dashboard.exploreVotes': 'Esplora voti',
    'dashboard.countryMonitor': 'Monitor paese',
    'dashboard.totalMeps': 'Totale MEP',
    'dashboard.politicalGroups': 'Gruppi politici',
    'dashboard.memberStates': 'Stati membri',
    'dashboard.trackedVotes': 'Voti tracciati',
    'dashboard.groups': 'Gruppi politici',
    'dashboard.seatsByCountry': 'Seggi per paese (Top 10)',
    'dashboard.recentVotes': 'Ultime votazioni chiave',
    'dashboard.viewAllVotes': 'Tutti i voti',
    'dashboard.passed': 'Approvato',
    'dashboard.rejected': 'Respinto',
    'dashboard.hemicycle': 'Emiciclo parlamentare',
    'dashboard.hemicycleDesc': '720 seggi per gruppo politico',
    'dashboard.mepTracker': 'Ricerca MEP',
    'dashboard.mepTrackerDesc': 'Cerca e filtra tutti i {count} eurodeputati',
    'dashboard.committeesDesc': 'Esplora 20 commissioni parlamentari e i loro membri',
    'dashboard.countryMonitorDesc': 'Analisi approfondita della rappresentanza di qualsiasi stato membro',
    'meps.title': 'Ricerca MEP',
    'meps.subtitle': 'Cerca i membri del Parlamento Europeo',
    'meps.searchPlaceholder': 'Cerca per nome o partito...',
    'meps.allCountries': 'Tutti i paesi',
    'meps.allGroups': 'Tutti i gruppi',
    'meps.allCommittees': 'Tutte le commissioni',
    'meps.results': '{count} risultato/i',
    'meps.clearFilters': 'Cancella filtri',
    'meps.noResults': 'Nessun MEP trovato',
    'meps.noResultsHint': 'Modifica i criteri di ricerca',
    'meps.previous': 'Precedente',
    'meps.next': 'Successivo',
    'meps.page': 'Pagina {current} di {total}',
    'meps.filters': 'Filtri',
    'votes.title': 'Esploratore voti',
    'votes.subtitle': 'Scopri come hanno votato i gruppi politici',
    'votes.byTopic': 'Voti per argomento',
    'votes.searchPlaceholder': 'Cerca votazioni...',
    'votes.found': '{count} voti',
    'votes.for': 'A favore',
    'votes.against': 'Contro',
    'votes.abstention': 'Astensione',
    'votes.passed': 'Approvato',
    'votes.rejected': 'Respinto',
    'votes.breakdown': 'Dettaglio voti per gruppo politico',
    'votes.group': 'Gruppo',
    'country.title': 'Monitor paese',
    'country.subtitle': 'Analisi della rappresentanza parlamentare di uno stato membro UE',
    'country.selectPrompt': 'Seleziona un paese',
    'country.selectDesc': 'Scegli uno stato membro dell\'UE',
    'country.meps': 'MEP da {country}',
    'country.nationalParties': 'Partiti nazionali',
    'country.epGroups': 'Gruppi PE',
    'country.genderBalance': 'Equilibrio di genere',
    'country.byParty': 'Per partito nazionale',
    'country.byGroup': 'Per gruppo PE',
    'country.partyToGroup': 'Partiti di {country} nei gruppi PE',
    'country.allMeps': 'Tutti i MEP da {country}',
    'country.searchPlaceholder': 'Cerca MEP da {country}...',
    'country.noResults': 'Nessun risultato',
    'country.outOf': 'su 720 totali',
    'committees.title': 'Esploratore commissioni',
    'committees.subtitle': 'Esplora le commissioni parlamentari e i loro membri',
    'committees.searchPlaceholder': 'Cerca commissioni...',
    'committees.selectPrompt': 'Seleziona una commissione',
    'committees.selectDesc': 'Scegli una commissione dalla lista',
    'committees.members': '{count} membri',
    'committees.groupComposition': 'Composizione per gruppo politico',
    'committees.topCountries': 'Principali paesi',
    'committees.membersList': 'Membri',
    'stats.title': 'Statistiche del Parlamento',
    'stats.subtitle': 'Statistiche complete sulla composizione del Parlamento Europeo',
    'stats.seatsByCountry': 'Distribuzione seggi per paese',
    'stats.genderBalance': 'Equilibrio di genere',
    'stats.groupSizes': 'Dimensione gruppi politici',
    'stats.countryGroups': 'Gruppi politici per paese (Top 15)',
    'stats.allCountries': 'Tutti i paesi',
    'stats.country': 'Paese',
    'stats.totalSeats': 'Totale seggi',
    'stats.mepsListed': 'MEP elencati',
    'stats.female': 'Donne',
    'stats.male': 'Uomini',
    'footer.title': 'OpenParliment - Esploratore dati del Parlamento Europeo',
    'footer.dataFrom': 'Dati da',
    'footer.portal': 'Portale Open Data del PE',
    'common.loading': 'Caricamento...',
    'common.error': 'Qualcosa è andato storto',
    'common.retry': 'Riprova',
    'common.allTopics': 'Tutti gli argomenti',
    'common.back': 'Indietro',
  },
};

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: 'English',
  pl: 'Polski',
  de: 'Deutsch',
  fr: 'Français',
  es: 'Español',
  it: 'Italiano',
};

const LanguageContext = createContext<LanguageContextValue>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('op-language');
    return (stored && stored in translations) ? stored as Language : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('op-language', lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
